### ISSUE TITLE
Export creation

### ISSUE THREAD

**Issue by socketubs** [errozero/acidmachine#2]
Such a nice project ! :smile: 
I saw that you just had "Save" and "New" buttons but it could be very nice to be able to export and save file :+1:

**Comment by errozero** [comment]
Hey, thanks.  I'm about to release a sequencer in the next few hours.

Export is high up on my list of things to add, i'm hopefully going to integrate this: https://github.com/mattdiamond/Recorderjs

**Comment by socketubs** [comment]
Great news !

**Comment by errozero** [comment]
Recorderjs is now integrated!  Recording wav files is now possible :)

**Comment by socketubs** [comment]
Perfect ! :+1:
